### ISSUE TITLE
인증 로직 구상 중 질문드립니다!

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#104]
인증 로직에 대해 고민하고 있습니다 ㅎㅎ 
직접 Nest로 대충 만들어보기도 하고 다른 프로젝트에서 OAuth 구현한 것 보기도 했는데, 어떤 방식이 제일 괜찮을지 몰라 질문드립니다. 

1. 인증 서버와의 인증을 프론트에서 다 처리(예> `react-oauth/google` 라이브러리 사용)하기보다는,  로그인하기 버튼 누르면 백엔드의 특정 엔드포인트(예> oauth2/google, oauth2/ft)로 이동하여 처리하는게 깔끔하다고 생각했습니다. 
2. 구글 oauth를 프론트에서 처리하면 왜인지는 모르겠지만 인증 서버에서 미리 적어놓은 callback으로 이동하지 않더라구요..? 그리고 42 oauth는 반드시 링크로 이동해서 인증을 하는 방식 하나밖에 안 되가지고, 이왕 하는거 구글 oauth도 방식을 똑같이 하는게 낫다고 생각했습니다. 
3. 백엔드의 callback 엔드포인트로 이동한 뒤 accessToken & refreshToken 정보를 쿠키로 저장하고 나서 특정 주소(아마 `/`)로 리다이렉션하는게 가장 깔끔하다는 생각을 했습니다. 

제 생각이 괜찮나요..?
의견 부탁드립니당

**Comment by jpham005** [comment]
@yoopark 일단...
oauth 를 통해 로그인을 하게 되면,
해당 서비스의 acess token이 발급되는데요.

이렇게되면 필연적으로 보안 문제가 생기게 됩니다.
특히 구글처럼 여기저기서 많이 쓰는 계정의 경우는 더 큰 문제를 불러올 가능성이 있죠.

때문에 구글에서 openid 라는 로그인용 서비스를 제공하고 있습니다.
acess token 을 발급하지 않고 로그인을 진행하는 방식인데요, 저희 서비스에서도 이런 방식을 채택해야 하지 않나 싶네요.

42 는 그런 서비스가 없기 때문에... 그냥 oauth로 진행해야 합니다.

정리하자면,
구글 openid 로 access token없이 로그인
42stat 자체적으로 만든 token 반환
42 oauth2 로 1회 인증

이렇게 될 것 같네요.

**Comment by yoopark** [comment]
오, openid라는게 있군요! 
찾아보니, 뭔가 `react-oauth/google`에서 제가 원래 했던 일이 openid였던 것 같네요..? 
그 라이브러리를 사용하면 그냥 유저 구글 프로필 정보가 jwt로 왔었거든요. 

정리하자면, 
1. google은 프론트에서 다 처리하고 jwt를 백엔드로 post하여 42stat의 accessToken & refreshToken을 (쿠키로든 response로든) 받아오는 방식
2. 42oauth는 백엔드의 특정 엔드포인트로 이동해서 callback url에서 요청하여 자체적으로 유저 프로필을 받아온 뒤 42stat의 
 accessToken & refreshToken을 (쿠키로든 response로든) 받아오는 방식

이런 느낌일까요?

**Comment by jpham005** [comment]
42 oauth 도 결국 프론트에서 42 페이지로 리다이렉션 하고 callback url 로 가는거죠.

로그인 방법 자체는 구글 로그인 하나로 한정짓는게 관리하기 편하지 않을까 싶긴 한데...
백엔드에서 유저를 어떻게 관리할지 명확한 계획이 있어야 확언할 수 있겠습니다.

**Comment by jpham005** [comment]
그리고 만약 구글로 로그인을 하고, 42는 인증용이라고 한다면,
access token 자체는 구글 로그인을 할 때 만들어줘야 할 것 같습니다.
음... token 은 response 로 주고, 브라우저의 session storage 이용해보면 어떨까라는 생각이 드는데,
저도 기존에 쿠키를 사용하는 방식만 구현해봤던지라, 이 부분은 공부가 필요합니다.

**Comment by yoopark** [comment]
ㅎㅎ 넵 알겠습니다! 그럼 일단 이정도로만 하고 본격적으로 인증 로직 제작하실 때 같이 고민해보는 걸로 하죠
