### ISSUE TITLE
함수 컨벤션 정리 및 리팩토링

### ISSUE THREAD

**Issue by niamu01** [42Statistics/42Stat-Backend#109]
naming
- [x] query -> getXXX
- [x] 나머지는 get 가능한 제거
- [x] result -> 변수 명 수정

argument
- [x] uid => userId
- [x] start, end => DateRange ( to, from 확인 )
  - [x] preferred~~ 페이지 분리
- [x] date 인자 => page service 에서 구하는 방식으로
- [x] start, end, currWeek, lastMonth => currWekk, lastMonth

refactor
- [ ] notfoundexception -> null반환으로 변경

**Comment by jpham005** [comment]
NotFoundException 에 대해선 후속 이슈에서 처리하기로 했습니다.
