### ISSUE TITLE
front 기준 api 설계

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Backend#13]
page 기준으로 나누기,
기존 작업물은 현재 설계가 완료된 후 다시 진행

**Comment by niamu01** [comment]
## MEMO:
### @objectType()
- PascalCase
- Enum, Type 명시 X

### @Field()
- camelCase
- 타입보다는 이름에 정보 명시 (score: ranking -> scoreRank: ranking)

### naming:
- 특정 시각마다 기록하는 형태(틱): Record
- Score는 코알리숑 점수 (과제 점수는 final mark)
- count -> cnt
- subject -> project
- ...

## 고민
#### 언제 블랙홀에 많이 빠질까? (기준: 서클, 유저수)
blackholedCircleType
-> blackholeUser: `blackholeUsers: [blackholeUser]`이 블랙홀 간 유저에 대한 정보 같음
-> blackholeCircle... ૮( ꒦ິ-꒦ີ)ა

#### 과제의 현재 등록 인원, 지금 가장 많은 사람이 참여한 과제는?
currTeamCount, projectTeamCnt: 팀 수가 아니라 인원수
-> 둘 다 currRegisteredCnt...

#### naming:
`AAs: [AA];` or `AA: [AA];` ??
