### ISSUE TITLE
레벨 증가 그래프 계산 로직 관련

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#188]
제 레벨이 11.05인데 그래프 상으로는 8.13으로 나오네요.
버그인가요?

<img width="752" alt="image" src="https://github.com/42Statistics/42Stat-Backend/assets/61629480/59d73479-cecf-4cda-aee6-02e652273753">

**Comment by jpham005** [comment]
안그래도 이 부분이 고민이 되는데요...
지금은 무조건 시작일 ~ 24개월간 레벨 변동을 프론트에 주고 있습니다.
근데 그러다 보니, 
- 입과한지 24개월이 지나지 않았거나
- 특정 일자부터 레벨 증가 기록이 24개월 내에 없으면
위와 같이 그래프가 일부분만 나옵니다.

요팍님의 경우 군 휴학으로 인해 24개월 내 레벨 변동이 더 없었던 것이죠.
이 부분을 어떻게 해야 좋을 지 저도 고민이 되네요,...

**Comment by yoopark** [comment]
꼭 2년으로 할 필요는 없을 것 같아요! 모두 시작일 기준으로 세고, 휴학 기간 동안에는 레벨이 가만히 있는 식으로 표시해도 괜찮을 듯합니다.

**Comment by jpham005** [comment]
그럼 요팍님 같은 경우에는 2020년 ~ 2023년 데이터를 모두 표시하게 되는걸까용?

**Comment by yoopark** [comment]
넵 4년 정도는 괜찮을 것 같긴 합니당

**Comment by jpham005** [comment]
회의 결과,
시작일 ~ 24개월 분 데이터,
기수 전체 평균, 기수 멤버 평균, 유저 데이터
이렇게 제공하는 것으로 변경 하기로 했습니다.
