### ISSUE TITLE
userPreview imgUrl undefined 타입 문의

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#208]
```
(parameter) userPreview: {
    __typename?: "UserPreview" | undefined;
    id: number;
    login: string;
    imgUrl?: string | null | undefined;
}
```

imgUrl에 undefined가 오는 경우는 어떤 상황인가요?

**Comment by jpham005** [comment]
그런 상황이 없긴 한데, graphql model 을 만들 때 null 을 반환하려면 nullable 하게 설정할 수 밖에 없는 것으로 알고 있습니다.
때문에 실제론 null 이 들어가기 위해서 imgUrl?: string 으로 타입이 만들어 진 것이지만,
프론트에서 보기엔 null 이나 undefined 가 들어갈 수 있는 것 처럼 보이는 것 이죵.

**Comment by yoopark** [comment]
그럼 string | null로 assertion해도 되나요?

**Comment by jpham005** [comment]
1. 가능합니다
2. 해당 구분이 필요한 경우가 뭔가용?
https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullabletype
NonNullable 타입으로 바꿔주면 되지 않을까 싶긴 하네요.

**Comment by jpham005** [comment]
@yoopark 관련해서 더 필요한 부분이 없다면 이슈 닫아주시면 됩니다.
