### ISSUE TITLE
coalition user 없는 경우에 대한 처리

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#215]
<img width="1173" alt="image" src="https://github.com/42Statistics/42Stat-Backend/assets/61629480/8a3b1d59-a9fe-41c8-8f96-e8d2cc50adae">

이미 아시겠지만, 혹시 해서 이슈 올립니다. 
프랑스에서 트랜스퍼한 유저입니다.

**Comment by yoopark** [comment]
DateTemplate(접속 시간, 주 접속 클러스터)를 제외하고 쿼리를 상단에서 한번 돌리기 때문에 에러 메시지가 같은 듯합니다.

**Comment by jpham005** [comment]
transfer 를 오는 경우 아직 생성되지 않았을 가능성이 있습니다. 이러한 경우에 대한 처리를 추가할 예정입니다.

**Comment by jpham005** [comment]
transfer 나 신규 입과생의 경우 이런 상황이 종종 발생할 수 있을거라 판단했고,
논의 결과 coalition 정보를 제외한 나머지 정보는 정상 제공할 수 있도록 해당 정보만 nullable 하게 변경하기로 했습니다.
