### ISSUE TITLE
ec2 배포 전 점검

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Backend#227]
- ec2 용량 확인 (db 와 app 모두 확인 필요)
- LB rate limit

**Comment by jpham005** [comment]
기존 env 이슈 내용

DB_ENDPOINT 변경하기
도커 -> 172.31.66.242:11900

**Comment by niamu01** [comment]
`du -hd <depth단계> <경로> 2>/dev/null | sort -hr`
debian goodies의 `dpigs -H`
를 통해 용량 확인

`deborphan`: 사용하지 않는 패키지 추가 검사
deborphan finds packages that have no packages depending on them. The default operation is to search only within the libs and oldlibs sec‐tions to hunt down unused libraries.
- libfwupdplugin1 아직 지우지 않음

삭제:
- (자동)
`sudo apt autoremove`
`sudo apt autoclean`
참고: https://askubuntu.com/questions/3167/what-is-difference-between-the-options-autoclean-autoremove-and-clean 

- (수동)
libgl1-mesa-dri

snapd 내부의 core 18, lxd, amazon-ssm-agent

python3 (python3.8 유지)

/home/ubuntu/.cache 내부 모두 삭제

`find /tmp -type f -delete` 로 /tmp 비우기

/var/log/journal에 로그가 계속 쌓이는데 관리하는 방법에는 개수 제한, 용량 제한, 기간 제한을 둘 수 있음
`journalctl --vacuum-time=7d` 를 통해 7일이상 된 로그는 삭제


mongodb

이후 지울 예정:
842M /home/ubuntu/.vscode-server
52M /home/ubuntu/.docker

**Comment by niamu01** [comment]
### db
cache가 아주 조금 있어 snapd와 libgl1-mesa-dri 만 지웠습니다

log file 위치:

**Comment by niamu01** [comment]
AWS WAF: https://repost.aws/knowledge-center/waf-apply-rate-limit
setting: https://repost.aws/knowledge-center/waf-apply-rate-limit

<img width="852" alt="image" src="https://github.com/42Statistics/42Stat-Backend/assets/74657997/c62299f2-1417-45da-abc3-e6f4160a4d76">

**Comment by jpham005** [comment]
현재 초당 70 페이지를 처리할 수 있기 때문에,
그에 맞춰 5분 당 80000 회로 설정했습니다.
