### ISSUE TITLE
scaleTeams service logic

### ISSUE THREAD

**Issue by niamu01** [42Statistics/42Stat-Backend#23]
### scaleTeams으로 계산할 수 있는 항목 service에 추가 & resolver 연결
- [x] Home의 이번주 총 평가 횟수 (currWeekEvalCnt)
- [x] Home의 지난주 총 평가 횟수 (lastWeekEvalCnt)
- [x] Home의 누적 평가 횟수 랭킹 (totalEvalCntRank) #랭킹
- [x] Home의 월간 평가 횟수 랭킹 (monthlyEvalCntRank) #랭킹
- [x] Personal/Evaluation의 평균 평가 점수 (averageFinalMark)
- [x] Personal/Evaluation의 평균 피드백 길이 (personalAverageFeedbackLength)
- [x] Personal/Evaluation의 평균 코멘트 길이 (personalAverageCommentLength)
- [x] Personal/Evaluation의 누적 평가 횟수 (totalCount)
- [x] Personal/Evaluation의 월간 평가 횟수 (currMonthCnt, lastMonthCnt)
- [x] Personal/Evaluation의 평균 평가 시간 (averageDuration)
- [x] Total의 역대 총 평가 횟수 (totalEvalCnt)
- [x] Total의 평균 피드백 길이 (averageFeedbackLength) #total 키워드를 붙일지 고민
- [x] Total의 평균 코멘트 길이 (averageCommentLength)
- [x] Personal/General->PERSONAL/EVAL(RE)의 누적 평가 횟수 (personalTotalEvalCnt)
    - [x] 이동
- [x] LOGSEARCH의 평가 로그 검색 (evalInfos) #필터링
    - [x] 이동

---

- [x] Total의 subject칸의 Pass/Fail비율 (pass_percentage) -> teams로 이동
- [x] Personal/General의 운명의 장난 스코어 (destiny_users) #랭킹 -> teams로 이동
- [x] PERSONAL- 이 유저를 평가자로 만난다면? #??? -> 자세한 기획 나올때까지 작업x

### 이후할일
- [ ] 필요한 type만 남기기
- [x] service -> service -> resolver 형태로 변경
- [x] 겹치는 로직 함수로 분리하기
    - [x] 시간 계산 로직 전부 추상화하기
    - [x] aggregation의 pipeline 분리하기

**Comment by jpham005** [comment]
@niamu01 
- Personal/General의 과제 기록
이거 곰곰이 생각해봐도 team api 인 것 같긴 한데용..?

**Comment by niamu01** [comment]
> @niamu01
> 
> * Personal/General의 과제 기록
>   이거 곰곰이 생각해봐도 team api 인 것 같긴 한데용..?

맞아요 이전에 이동하기로 했었죠..!
지우기로 한 것도 몇 개 남아있어서 [discussion](https://github.com/42Statistics/42Stat-discussion/discussions/13)에 같이 업데이트했습니다.
만들다가 안맞는 api가 있으면 수정해주세용 🙇

**Comment by jpham005** [comment]
그럼 이 부분은 제가 작업할만한게 없네용.
오늘은 db 연결을 해보겠습니다

**Comment by jpham005** [comment]
eval log 검색 인자에서 과제는 project api고,
타입 줄이는건... 나중에 해도 될 것 같아요.
이슈 종료하겠습니다.
