### ISSUE TITLE
to jimlee 평가로그 검색 시 에러

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#248]
<img width="1186" alt="image" src="https://github.com/42Statistics/42Stat-Backend/assets/61629480/67d4d79f-1a59-45a3-9fe5-b722319f79c6">

**Comment by jpham005** [comment]
아니 이거 송피디님이 평가하셔서 생기는 문제네요....

**Comment by jpham005** [comment]
- #253 을 통해 해결할 예정입니다.
