### ISSUE TITLE
DestinyUsers 관련 이슈

### ISSUE THREAD

**Issue by lev-Zero** [42Statistics/42Stat-Backend#26]
query {
  getPersonGeneralPage {
    evalUserInfo {
      destinyUsers {
        id
        login
        imgUrl
        score
      }
    }
  }
}

**운명의 장난 스코어 불러 오는 쿼리인데 질문이 있습니다**

1 .다른 랭킹 리스트들은 userPreview라는 타입을 이용하는데 재사용 하지 않으신 이유가 있으신지
2. imgUrl 의 타입이 any인데 아직 임시라서 그런건가용?

확인 부탁드립니다~

**슬랙 메세지 결과 자함님의 답변**

1.아마 score가 없어서 그럴거에요. 내부적으로는 재사용하는 걸로 압니다.
2. url | null로 되어야 하는데 확인이 필요해보이네요.

**Comment by jpham005** [comment]
말씀드린 것 처럼 DestinyUser는 UserPreview를 상속받는 방식으로 구현을 했구요, 프론트 입장에서만 다른 타입으로 보이는게 맞습니다.
imgUrl 같은 경우는, 백엔드에선 정상적으로 설정이 되어 있고, graphql playground 에서도 URL 타입이라고 잘 나와서 이유를 모르겠네요.
프론트에서 type generate 했을 때 어떻게 되는지 확인이 필요할 것 같습니다.

**Comment by jpham005** [comment]
확인 결과, DateTime, URL이 custom scalar 로 사용중인 타입들이라, 프론트에서 처리를 해야하는게 맞긴 하네요.
앞으로 cutsom scalar 사용하게되면 알려드리겠습니다.
현재 필요한 수정 사항은 프론트에 풀리퀘 올리겠습니다.
