### ISSUE TITLE
월간 평가 횟수 0회일 때 column 자체가 안옴

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#280]
<img width="1435" alt="image" src="https://github.com/42Statistics/42Stat-Backend/assets/61629480/1d70dcc1-8aa1-4544-9725-ef302bff8015">

평가 횟수가 0회라면 column 자체가 안 오는 것이 아니라 0회 column이 와야할 것 같아요.

예) 2월 말, 5월 말

**Comment by jpham005** [comment]
#275 issue 에서 이미 조치한 부분입니다.
main branch 에만 병합되어있고, aws 에는 배포되지 않은 상황입니다.
로컬에서 작업해도 같은지 확인해주세요.
