### ISSUE TITLE
기수별 랭킹

### ISSUE THREAD

**Issue by niamu01** [42Statistics/42Stat-Backend#324]
- [x] fullprofile 을 통해 promo 추가
- [ ] rank 인덱싱 필터링 후 다시 매기기

todo: 기수 관리 방법에 대해 고민 중

**기존 feat/promoRanking 브랜치 삭제 후 작업 부탁드립니다**

**Comment by jpham005** [comment]
기존 작업 방식보다,
유저 데이터에 기수 데이터를 저장하는 편이 더 정확한 기수 분류를 할 수 있는 방법이라,
db 에 임시로 작업하고, 이를 이용하여 기수 정보를 반환하려 합니다.

**Comment by jpham005** [comment]
프론트 로직 상 기수 정보를 따로 제공하는게 낫다고 판단하여 해당 부분 다시 작업하기로 했습니다.
