### ISSUE TITLE
기획 재검토에 따른 백엔드 변경 사항 정리

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#88]
> 피그마의 **v2.1** 페이지들을 보시면 대략적인 생김새를 알 수 있습니다.   
> 팀 노션의 **[기획 재검토]** 페이지를 읽어보시면 수정 배경 및 의도를 알 수 있습니다.   

백엔드 구조를 정확히 아는건 아니라서 제가 임의로 나누기보단 프론트 페이지 기준으로 설명드리겠습니다.  
수정사항에 대해서만 말씀드리겠습니다.  

> 2023-06-09 LandingPage & HomePage 개인화 카드 내용 확정하였습니다. 

## LandingPage (확정)
- **은하수를 여행한지 982일째** : 첫 42서울 ~~라 피신~~ 본 과정 시작일로부터 현재일 -> 시작일 주시면 됩니다 #146 
- **810명의 히치하이커와 함께 여행중** : 현재 생존 유저 수 #146 

### Strings
- **지금까지 블랙홀을 마주한 111명** : 누적 블랙홀 유저 수 #146
- **PUSH_SWAP과 싸우는 32명** : 현재 가장 많은 사람이 참여하는 과제와 유저 수 #169 
- **자기만의 여행을 시작한 231명** : Member 수 #146 
- **87,201번째 평가가 지금 진행 중** : 누적 평가 횟수 #146 

### 개인화 카드 (확정)
- **🎉🎉 Member 달성 축하드려요 🎉🎉** : Member 달성한지 7일 이내의 경우 #144 
  - 받고 싶은 값 : True/False #144 
- **2일 전에 push_swap을 통과하셨네요! 축하드려요 🎉** : 통과한지 2일 이내의 과제가 있는 경우 (Exam 포함, 2일 이내에 여러개의 과제를 통과한 경우 가장 최신의 통과한 과제 하나만 반환) #144 
  -  받고 싶은 값 : 가장 최근 통과한 과제와 통과 시간 (libft도 안 통과했으면 null, null) #144 
- **13일 앞에 블랙홀이 보여요 👀 조심하세요** : 블랙홀 남은 일수가 7 ~ 21일 사이인 경우 #144 
  - 받고 싶은 값 : 블랙홀 남은 일수 (멤버면 null) #144 
- **DON'T PANIC! You can do it 💙** : 블랙홀이 7일 미만인 경우 #144 
  - 받고 싶은 값 : 위와 통합 #144 
- **대단해요! 주간 경험치 증가량 2위를 차지했어요 🏅**  : 주간 경험치 증가량 / 주간 코알리숑 스코어 / 주간 평가 횟수 랭킹 1 ~ 3위에 해당하는 유저인 경우 #144 
  - 받고 싶은 값 : 주간 경험치 증가량 순위, 주간 코알리숑 스코어 순위, 주간 평가 횟수 순위 #144 
- 해당 사항 없을 경우 : 기타 프로그래밍 명언 (프론트에서 관리)

우선순위대로 작성하긴 했는데, 해당되는 내용 다 주시면 프론트에서 우선순위에 따라 띄우겠습니다.

### 기타
- 주간 1인당 평가 횟수 : 주간 총 평가 횟수를 활성화 유저 수로 나눈 값 #135 
- Member 비율 : Member / Learner로 구분. 비활성화 유저도 직전 상태로 포함하여 산정 #137 
- 블랙홀 유저 비율 : Blackhole / Survived로 구분. 비활성화된 Member도 Survived에 포함하여 산정 #137
- 이번 달 누적 코알리숑 티그 횟수 : **이번 달 누적 블랙홀 인원**과 똑같이, 이번 달 기준일을 0으로 시작하여 일마다 갱신 #126 

## ProfileGeneralTab
> ProfileInfo에 있던 내용 다수를 ProfileGeneralTab으로 내려 표시
- 본과정 시작일 #103 
- 전체 코알리숑 스코어 랭킹은 표시 안 하는 걸로 수정 #126
  - 논의 결과 다시 표시하는 것으로 결정 #126

### TeamInfo
- 팀명 #138 
- 팀 빌딩 / 진행 중 / 평가 중 / 완료 4가지 상태로 나누어 일자 제공(또는 등록일, locked된 일, 제출일, 채점 완료일 4개 제공) #138

## ProfileEvalTab
- **이 유저를 평가자로 만난다면?** 카드 잠정 삭제 #103 
- 누적 평가 시간 #135 
- 최근 받은 피드백 #135 

## ProjectPage
> ProjectInfo 카드를 ProjectPage로 분리. NavBar의 검색창에서 유저 뿐 아니라 프로젝트도 검색할 수 있도록 변경 (Intra 로직과 동일)

- 인원, 기간, 경험치 정보 #80 
- 평균 소요기간 : 모두가 과제를 등록하고 시작하는 게 아니므로 수치가 무의미할 것으로 예상됨. 삭제.  #80 

## EvalLogSearchPage
- **검색결과 32,801건** : 검색결과 개수를 미리 제공해주어야 함 #105 
- 최신순 / 오래된순 필터 추가 #135 

## LeaderBoardPage
- 보유 평가 포인트, 보유 월렛 랭킹은 별로 중요하지 않은 정보임. HomePage의 카드로 이동. #103 
- 레벨 랭킹 : 누적 #103 
- 경험치 증가량 : 주간, 월간 #137 
- 평가 횟수 : 주간, 월간, 누적 #103 
- 코알리숑 스코어 : 주간, 월간, 누적 #126 
- 50명씩 페이지네이션하여 제공 (42 Evaluators 로직과 동일) #105 
- 현재 로그인한 유저 자신의 등수를 미리 제공해주어야 함 #103

**Comment by jpham005** [comment]
모두 구현 완료되어 해당 이슈 닫습니다.
