### ISSUE TITLE
User 데이터 적용 중 FE 요청사항

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#99]
1. ProfilePage, profileGeneralPage, profileEvalPage의 인자로 uid 대신 username으로 교체하였으면 합니다. 
현재 저희가 `profile/me`, `/profile/yopark`의 양식으로 라우팅한 뒤, 해당 param 정보를 읽어 누군지 확인하는 로직으로 진행 중입니다. 그런데 uid로 검색을 해야하니 username으로 uid를 찾는 방법이 없어 애매한 상황입니다. 

2. 보유 평가 포인트 랭킹(correctionPointRanks)와 보유 월렛 랭킹(walletRanks)의 기본 제공 데이터를 3개 -> 5개로 늘려주시면 감사하겠습니다. 
중요한 것은 아니지만, 바뀐 기획 상에는 최대 5등까지 띄우도록 되어 있습니다. 

3. 활성화 유저 수 추이(activeUserCountRecords) 맨 처음에 1970년 데이터가 하나 오는 것 같습니다. 확인 부탁드립니다. 
4. personal~ 관련 쿼리를 보냈을 때 coalition이 undefined일 수도 있다고 나오는데, coalition이 없는 경우가 있는지 확인해주시고 만약 coalition이 확실히 온다면 타입 변경 부탁드립니다. 
5. 유저 검색 시 유저 사진 url도 함께 주시면 감사하겠습니다.

**Comment by jpham005** [comment]
@yoopark @niamu01 
1. 사실 이건 둘 다 처리가 되는게 맞는 것 같네요.
2. 이건 금방 될 것 같긴 하구요, 프론트에서 인자 넣을 수 있도록 되어있을겁니다... 만약 인자 넣는것도 안되면 그것도 수정해야겠네요.
3. 아마 백엔드 로직 상 그런 데이터가 넘어갈 가능성이 있어보이긴 합니다. 확인해볼게요.
4. intra api 상으론 undefined 일 가능성이 있는게 맞지만(피신하는 사람들), 우리 서비스에선 없을 것 같습니다. 수정하는게 나을 것 같네요.
5. imgUrl 필드가 없나요? 확인해보겠습니다.

**Comment by yoopark** [comment]
2. 아 limit 인자가 있었군요. 못봤습니다 ㅎㅎ

**Comment by jpham005** [comment]
근데 뭐 기본값 맞춰두는게 나을 것 같긴 해요. 아마 예주님이 나중에 수정하실겁니다.

**Comment by niamu01** [comment]
@yoopark 
현재 activeUser에서
```
{
  at: 2023-02-28T15:00:00
  value: 937
}
```
인 경우 2/28 시점의(2/1-2/28간 신규기수&블랙홀유저가 적용된) value입니다..!
